const seed=[{id:1,name:"Black Label Whisky",cat:"Whisky",price:85000,stock:10,icon:"🥃"},{id:2,name:"Smirnoff Vodka",cat:"Vodka",price:45000,stock:15,icon:"🍸"},{id:3,name:"Gordon's Gin",cat:"Gin",price:55000,stock:12,icon:"🍸"},{id:4,name:"Captain Morgan Rum",cat:"Rum",price:60000,stock:8,icon:"🍹"},{id:5,name:"Jose Cuervo Tequila",cat:"Tequila",price:90000,stock:6,icon:"🥃"},{id:6,name:"Baileys Irish Cream",cat:"Liqueurs",price:75000,stock:7,icon:"🍮"}];
let products=JSON.parse(localStorage.vp_products||"null")||seed,cart=JSON.parse(localStorage.vp_cart||"{}");const cocktails=[["B15","Signature cocktail",18000],["Black Russian","Vodka & coffee liqueur",18000],["White Russian","Vodka, coffee liqueur & cream",20000],["Classic Martini","Gin/vodka & dry vermouth",20000],["Sex on the Beach","Vodka, peach, orange & cranberry",22000],["Tequila Sunrise","Tequila, orange & grenadine",20000],["Bugolobi Sunrise","Velvet Pour signature",24000],["Mudslide","Vodka, coffee liqueur & cream",24000],["Shirley Temple","Ginger ale, grenadine & citrus",12000],["Pink Sprite","Sprite, strawberry & citrus",12000],["Blue Lagoon","Blue citrus & lemonade",14000]];
const money=n=>"UGX "+Number(n).toLocaleString(),count=()=>Object.values(cart).reduce((a,b)=>a+b,0),save=()=>{localStorage.vp_products=JSON.stringify(products);localStorage.vp_cart=JSON.stringify(cart)};
function nav(){return `<header><nav><div class="logo">VELVET <span>POUR</span></div><div class="row"><button onclick="go('home')">Home</button><button onclick="go('shop')">Liquor</button><button onclick="go('cocktails')">Cocktails</button><button onclick="go('booking')">Events</button><button onclick="go('cart')">Cart (${count()})</button><button onclick="go('admin')">Admin</button></div></nav></header>`}
function shell(x){document.body.innerHTML=nav()+`<main class="wrap">${x}</main><footer>Velvet Pour • Liquor • Cocktails • Delivery • Mobile Bar</footer>`}
function go(p){location.hash=p;render()}function render(){let p=location.hash.slice(1)||"home";({home,shop,cocktailsPage,cartPage,booking,admin}[p]||home)()}
function home(){shell(`<section class="hero"><div class="kicker">PREMIUM DRINKS & EXPERIENCES</div><h1>VELVET<br>POUR</h1><p>Shop liquor, order cocktails, book our mobile bar and arrange delivery from one place.</p><div class="row"><button class="btn" onclick="go('shop')">Shop liquor</button><button class="btn dark" onclick="go('booking')">Book mobile bar</button></div></section><h2>Explore Velvet Pour</h2><div class="grid"><div class="card"><div class="visual">🍾</div><h3>Liquor Store</h3><p class="muted">Expand your catalogue from Admin.</p></div><div class="card"><div class="visual">🍸</div><h3>Cocktails</h3><p class="muted">Alcoholic and non-alcoholic selections.</p></div><div class="card"><div class="visual">🎉</div><h3>Events</h3><p class="muted">Request the Velvet Pour mobile bar.</p></div></div>`)}
function shop(){shell(`<div class="row"><h2>Liquor Store</h2></div><div class="row">${["All",...new Set(products.map(x=>x.cat))].map(c=>`<button class="outline" onclick="showCat('${c}')">${c}</button>`).join("")}</div><br><div id="plist" class="grid"></div>`);showCat("All")}
function showCat(c){document.getElementById("plist").innerHTML=(c=="All"?products:products.filter(x=>x.cat==c)).map(p=>`<div class="card"><div class="visual">${p.icon||"🍾"}</div><small class="muted">${p.cat} • Stock ${p.stock}</small><h3>${p.name}</h3><div class="gold">${money(p.price)}</div><br><button class="btn" onclick="add(${p.id})">Add to cart</button></div>`).join("")||"<p class='muted'>No products yet.</p>"}
function add(id){cart[id]=(cart[id]||0)+1;save();go("shop")}
function cocktailsPage(){shell(`<h2>Cocktail Menu</h2><div class="grid">${cocktails.map((c,i)=>`<div class="card"><div class="visual">🍸</div><small class="muted">${i<8?"Alcoholic":"Non-alcoholic"}</small><h3>${c[0]}</h3><p class="muted">${c[1]}</p><div class="gold">${money(c[2])}</div><br><button class="btn" onclick="addCocktail('${c[0]}',${c[2]})">Add</button></div>`).join("")}</div>`)}
function addCocktail(n,p){let k="c_"+n.replace(/\W/g,"_");cart[k]=(cart[k]||0)+1;localStorage["vp_"+k]=JSON.stringify({name:n,price:p});save();go("cocktails")}
function cartPage(){let items=[],sub=0;for(let k in cart){let p=k.startsWith("c_")?JSON.parse(localStorage["vp_"+k]):products.find(x=>x.id==k);if(!p)continue;sub+=p.price*cart[k];items.push(`<div class="card"><div class="row" style="justify-content:space-between"><b>${p.name}</b><span>${money(p.price*cart[k])}</span><span><button class="outline" onclick="qty('${k}',-1)">−</button> ${cart[k]} <button class="outline" onclick="qty('${k}',1)">+</button></span></div></div>`)}let d=items.length?5000:0;shell(`<h2>Your Cart</h2>${items.join("")||"<div class='notice'>Your cart is empty.</div>"}${items.length?`<div class="card"><div>Subtotal: <b>${money(sub)}</b></div><div>Delivery estimate: <b>${money(d)}</b></div><div class="total">Total: ${money(sub+d)}</div><br><button class="btn" onclick="checkout(${sub+d})">Proceed to checkout</button></div>`:""}`)}
function qty(k,d){cart[k]+=d;if(cart[k]<=0)delete cart[k];save();render()}
function checkout(total){shell(`<h2>Checkout</h2><p class="muted">Prototype checkout — live payment integration comes next.</p><form class="form" onsubmit="place(event)"><input id="name" required placeholder="Full name"><input id="phone" required placeholder="Phone number"><input id="addr" required placeholder="Delivery address / area"><select id="pay"><option>Mobile Money</option><option>Card</option><option>Cash on delivery</option></select><div class="notice">Total: <b>${money(total)}</b></div><button class="btn">Place order</button></form>`)}
function place(e){e.preventDefault();localStorage.vp_order=JSON.stringify({name:name.value,phone:phone.value,address:addr.value,payment:pay.value,cart,date:new Date().toISOString()});cart={};save();alert("Order saved in prototype.");go("home")}
function booking(){shell(`<h2>Book Velvet Pour</h2><p class="muted">Mobile bar for weddings, birthdays, corporate events and private functions.</p><form class="form" onsubmit="bookSave(event)"><input id="bn" required placeholder="Your name"><input id="bp" required placeholder="Phone number"><select id="bt"><option>Birthday</option><option>Wedding</option><option>Corporate event</option><option>Private party</option><option>Other</option></select><input id="bd" type="date" required><input id="bg" type="number" min="1" required placeholder="Expected guests"><input id="bl" required placeholder="Event location"><textarea id="notes" rows="4" placeholder="Package / special requests"></textarea><button class="btn">Send booking request</button></form>`)}
function bookSave(e){e.preventDefault();localStorage.vp_booking=JSON.stringify({name:bn.value,phone:bp.value,type:bt.value,date:bd.value,guests:bg.value,location:bl.value,notes:notes.value});alert("Booking request saved.");go("home")}
function admin(){shell(`<div class="card"><h2>Admin Catalogue</h2><p class="muted">Add new liquor/products yourself.</p><form class="form" onsubmit="addProduct(event)"><input id="pn" required placeholder="Product name"><input id="pc" required placeholder="Category"><input id="pp" type="number" required placeholder="Price UGX"><input id="ps" type="number" min="0" required placeholder="Stock"><input id="pi" maxlength="2" placeholder="Emoji e.g. 🥃"><button class="btn">Add product</button></form></div><h2>Catalogue</h2><div class="grid">${products.map(p=>`<div class="card"><b>${p.name}</b><p class="muted">${p.cat} • ${money(p.price)} • stock ${p.stock}</p><button class="outline" onclick="removeProduct(${p.id})">Remove</button></div>`).join("")}</div><br><div class="notice">For production, secure this dashboard with authentication and a backend database.</div>`)}
function addProduct(e){e.preventDefault();products.push({id:Date.now(),name:pn.value,cat:pc.value,price:+pp.value,stock:+ps.value,icon:pi.value||"🍾"});save();alert("Product added.");render()}function removeProduct(id){products=products.filter(p=>p.id!==id);save();render()}
window.go=go;window.showCat=showCat;window.add=add;window.addCocktail=addCocktail;window.qty=qty;window.checkout=checkout;window.place=place;window.bookSave=bookSave;window.addProduct=addProduct;window.removeProduct=removeProduct;render();